Add github actions for tests and release
canonical/charm-storage-connector pull request #13
Opened 2023-12-07 09:27 UTC by sudeephb

Add actions from bootstack-charms-spec

2023-12-08 09:44 UTC, sudeephb commented
I have manually added the maintainers and admin permissions for the relevant teams.

2023-12-11 01:12 UTC, Pjack approved these changes

2023-12-11 14:26 UTC, rgildein requested changes
Ci needs to be enabled first.

2023-12-11 18:37 UTC, agileshaw requested changes
Admin needs to add JIRA_URL to Github secrets and set up sonar project to enable those integrations

2023-12-11 18:37 UTC, agileshaw commented on .github/CODEOWNERS
> +# later match takes precedence, @canonical/bootstack will be requested for
This needs to be updated as well
```suggestion
# later match takes precedence, @canonical/soleng-reviewers will be requested for
```

2023-12-13 08:26 UTC, Pjack approved these changes

2023-12-13 09:53 UTC, jneo8 commented on .github/CODEOWNERS
> +# later match takes precedence, @canonical/bootstack will be requested for
`JIRA_URL` is there.

2023-12-13 10:35 UTC, closed without merging

2023-12-13 10:35 UTC, jneo8 commented
Please move the discussion to #15 , the checks is running there.